# Default configuration template for CNN model
model:
  type: "cnn"
  num_classes: 10
  in_channels: 3
  hidden_dim: 512
  dropout: 0.1

data:
  type: "image"
  data_path: "./data"
  image_size: [224, 224]
  batch_size: 32
  num_workers: 4
  shuffle: true
  pin_memory: true

training:
  num_epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adam"
  scheduler: "step"
  step_size: 30
  gamma: 0.1
  gradient_clip: 1.0
  save_every: 10
  eval_every: 1

evaluation:
  task_type: "classification"

experiment:
  name: "cnn_experiment"
  output_dir: "./outputs"
  seed: 42
  device: "auto"  # auto, cpu, cuda
