# Example CNN configuration
model:
  name: "simple_cnn"
  in_channels: 1
  num_classes: 10
  hidden_channels: [32, 64, 128]

data:
  name: "mnist"
  data_path: "./data"
  download: true
  normalize: true
  preprocessor:
    name: "mnist"
    normalize: true
  train:
    split: "train"
  validation:
    split: "test"

training:
  num_epochs: 10
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 1e-4
  optimizer: "adam"
  scheduler: "step"
  step_size: 5
  gamma: 0.5
  loss: "cross_entropy"
  gradient_clip: 1.0
  save_interval: 5
  eval_interval: 1
  log_interval: 10
  use_tensorboard: true

experiment:
  seed: 42
  output_dir: "./exp/mnist_cnn_exp"
  device: "auto"
